# CircleCI configuration file

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Imagen de Docker para Java 8
    steps:
      - checkout
      - run:
          name: Show Commit Info
          command: |
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            COMMIT_HASH=$(git rev-parse --short HEAD)
            echo "Corriendo CircleCI por commit: $COMMIT_MESSAGE ($COMMIT_HASH)"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
